Update stream_engine.hpp
The Intel compiler complains about the order of "static" and "const". The fix is a simple switch to one line in one header file.

In file included from ipc_listener.cpp(29):
stream_engine.hpp(97): error #82: storage class is not first
          const static size_t greeting_size = 12;