Add missing <new> includes for std::nothrow
Without the <new> include, compilation may fail:

```
src/polling_util.hpp:28:30: error: no member named 'nothrow' in namespace 'std'
   28 |             _buf = new (std::nothrow) T[nitems_];
      |                              ^~~~~~~
```